obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_main.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_spi.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_plat_qcom.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_ic.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_touch.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_mp.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_hostdl.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_node.o
